USE HR;

DESC emp;
DESC dept;

CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR(20) PRIMARY KEY,
    PASSWORD VARCHAR(100) NOT NULL,
    MEMBER_NAME VARCHAR(20) NOT NULL,
    ROLE VARCHAR(10) NOT NULL DEFAULT 'USER'
);

SELECT *
FROM MEMBER
WHERE MEMBER_ID = 'admin';

INSERT INTO MEMBER
    (MEMBER_ID, PASSWORD, MEMBER_NAME, ROLE)
VALUES
    ('admin', '$2a$10$9OcvxCELAsBZiKPjLWzJkuO7x4EHL7VATegZpTUJEvw4JM3V78t.C', '관리자', 'ADMIN');
