USE HR;

DESC emp;
DESC dept;

CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR(20) PRIMARY KEY,
    PASSWORD VARCHAR(100) NOT NULL,
    MEMBER_NAME VARCHAR(20) NOT NULL,
    ROLE VARCHAR(10) NOT NULL DEFAULT 'USER'
);



INSERT INTO MEMBER (
    MEMBER_ID,
    PASSWORD,
    MEMBER_NAME,
    ROLE
)
VALUES (
    'admin',
    '$2a$10$ZIWhGB4Hgy//rh75IS.lt.AowytEArTYqLhkTM5NPIHNrw7elcMgC',
    '관리자',
    'ADMIN'
);
SELECT MEMBER_ID, MEMBER_NAME, ROLE
FROM MEMBER
WHERE MEMBER_ID = 'admin';



UPDATE MEMBER
SET PASSWORD = '$2a$10$p9fl9V9nPH1Cy7c8RJ572O6IQhMxjFiSAO3Z5BX8zVFFKQ85XWFq6'
WHERE MEMBER_ID = 'admin';

COMMIT;

SELECT MEMBER_ID, ROLE, CHAR_LENGTH(PASSWORD) AS password_length
FROM MEMBER
WHERE MEMBER_ID = 'admin';

INSERT INTO MEMBER (
    MEMBER_ID,
    PASSWORD,
    MEMBER_NAME,
    ROLE
)
VALUES (
    'user1',
    '$2a$10$CaLmhWcRAYJOkF06SDV94urhb9YebmeMiVCqTp/mW8Hqs8GdIvkkC',
    '일반사용자',
    'USER'
);

COMMIT;

-- 현재 선택된 DB 확인
SELECT DATABASE();

-- 테이블 목록 확인
SHOW TABLES;

-- 부서 테이블의 컬럼·외래키 확인
SHOW CREATE TABLE dept;

SELECT LOCAL_CODE
FROM location;

SELECT DEPT_ID, COUNT(*) AS 사원수
FROM emp
WHERE DEPT_ID IS NOT NULL
GROUP BY DEPT_ID;

-- 1. MEMBER 테이블에 로그인 상태 컬럼 추가

ALTER TABLE MEMBER
    ADD COLUMN LOGIN_FAIL_COUNT INT NOT NULL DEFAULT 0,
    ADD COLUMN IS_LOCKED INT NOT NULL DEFAULT 0,
    ADD COLUMN LAST_LOGIN_AT DATETIME NULL;

    USE HR;

SELECT MEMBER_ID, LOGIN_FAIL_COUNT, IS_LOCKED, LAST_LOGIN_AT
FROM MEMBER;

-- 'user1'을 테스트한 계정 아이디로 변경
UPDATE MEMBER
SET LOGIN_FAIL_COUNT = 0,
    IS_LOCKED = 0
WHERE MEMBER_ID = 'admin';

COMMIT;